about:
  home: https://github.com/avengerpb/snmf_conda
  license: Artistic-2.0
  summary: Estimating individual admixture coefficients based on sparse non-negative matrix factorization and population genetics

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: False

requirements:
  build:
    - perl-bioperl
    - libgcc
    - perl-lib

package:
  name: snmf
  version: 1.0.0

source:
   fn: 1.7.tar.gz
   url: https://github.com/avengerpb/snmf_conda/archive/1.7.tar.gz
   md5: fa3c2cd605e49c337b105e8b5c2206fc

test:
 command:
  - snmf.sh test.vcf out logs k_out k_log 2 5 ab
