about:
  home: https://github.com/avengerpb/snmf_conda
  license: Artistic-2.0
  summary: Estimating individual admixture coefficients based on sparse non-negative matrix factorization and population genetics

build:
  detect_binary_files_with_prefix: true
  number: 0
  skip: False

requirements:
  run:
    - perl
    - perl-bioperl
    - gcc

package:
  name: snmf
  version: 1.0.0

source:
 - url: https://github.com/avengerpb/snmf_conda/archive/1.0.tar.gz
   folder: git
   md5: 30ac757e1acb408221bd57882bd227b2
 - url: http://membres-timc.imag.fr/Olivier.Francois/snmf/files/sNMF_CL_v1.2.zip
   folder: temp
   md5 713c30e00710db617ae64dd0eccc1a53
