about:
  home: https://github.com/avengerpb/snmf_conda
  license: Artistic-2.0
  summary: Estimating individual admixture coefficients based on sparse non-negative matrix factorization and population genetics

build:
  number: 0
  skip: False

requirements:
  build:
    - perl-bioperl
    - perl-lib

package:
  name: snmf
  version: 1.0.0

source:
   fn: 1.3.tar.gz
   url: https://github.com/avengerpb/snmf_conda/archive/1.3.tar.gz
   md5: 62578b7bdb3cc1f52f746c71dc276f1d

test:
 command:
  - snmf.sh test.vcf out logs k_out k_log 2 5 ab
